SELECT
CASE
when deptno = 10 then 'Ten'
when deptno = 20 then 'Twenty'
when deptno = 30 then 'Thirty'
when deptno = 40 then 'Fourty'
when deptno = 50 then 'Fifty'
when deptno = 60 then 'Sixty'
when deptno = 70 then 'Seventy'
when deptno = 80 then 'Eighty'
when deptno = 90 then 'Ninety'
when deptno = 100 then 'Hundred'
when deptno = 10 then 'One Hundred Ten'
when deptno = 10 then 'One Hundred Twenty'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'when deptno = 10 then 'Ten'when deptno = 10 then 'Ten'when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
when deptno = 10 then 'Ten'
